class RedisKeys:
    OPENROUTER_MODEL = "settings:openrouter_model"
    IMAP_SERVER = "settings:imap_server"
    IMAP_USERNAME = "settings:imap_username"
    IMAP_PASSWORD = "settings:imap_password"
    OPENROUTER_API_KEY = "settings:openrouter_api_key"
    DRAFT_CREATION_ENABLED = "settings:draft_creation_enabled"
    SYSTEM_PROMPT = "agent:system_prompt"
    TRIGGER_CONDITIONS = "agent:trigger_conditions"
    USER_CONTEXT = "agent:user_context"
    LAST_EMAIL_UID = "last_email_uid"
    FILTER_RULES = "agent:filter_rules" 